### ISSUE TITLE
FID score: Complex number Error 

### ISSUE THREAD

**Issue by Hossein-Askari** [rakhimovv/GenerativeLatentFlow#1]
I have tried a few times the generative latent flow model for Cifar10 dataset, but I have always got this error after a few epochs, (Imaginary or complex number in FID score), which stems from the following line in fid_score.py. I would really appreciate it if you could let us know how to fix this issue. 

raise ValueError('Imaginary component {}'.format(m))

**Comment by fursovia** [comment]
Probably, something's wrong with latent representations. Could you share the code of how you obtained these representations?

**Comment by Hossein-Askari** [comment]
Thanks. I did not change anything, I run exactly the same code with fixed options you have chosen for cifar10 dataset.

**Comment by Hossein-Askari** [comment]
> Probably, something's wrong with latent representations. Could you share the code of how you obtained these representations?

Thanks. I did not change anything, I run exactly the same code with fixed options you have chosen for cifar10 dataset.

**Comment by Hossein-Askari** [comment]
I am wondering if you come up with any idea how to solve this problem?

**Comment by fursovia** [comment]
I still would like to be able to reproduce your error. Could you share the images for which you are getting this error?

**Comment by Hossein-Askari** [comment]
> I still would like to be able to reproduce your error. Could you share the images for which you are getting this error?

So, it means you are not getting such error on your machine? To be honest, I do not know what you mean by producing images. 

The error arises when calculating the frechet_distance. 
#numerical issues
    if np.iscomplexobj(matrix_sqrt):
        if not np.allclose(np.diagonal(matrix_sqrt).imag, 0, atol=1e-3):
            m = np.max(np.abs(matrix_sqrt.imag))
            import pdb; pdb.set_trace()
            raise ValueError('Imaginary component {}'.format(m))
        matrix_sqrt = matrix_sqrt.real

**Comment by fursovia** [comment]
Could you run 

```bash
PYTHONPATH=. python glf/metrics/fid_score.py
```

Does this error occur?

**Comment by Hossein-Askari** [comment]
> Could you run
> 
> ```shell
> PYTHONPATH=. python glf/metrics/fid_score.py
> ```
> 
> Does this error occur?

Hi. Sorry for late reply, I did not see your message. 
No. I run PYTHONPATH=. python glf/metrics/fid_score.py; I did not get any error.

**Comment by Hossein-Askari** [comment]
Hi Ivan,
Thanks.

I did run, and I did not get any error for this PATH. But I am wondering if
this is related to the model's fid score?.

**Comment by fursovia** [comment]
What this script does is it calculates the FID score for some random images:

```python
predictor = InceptionPredictor(output_dim=64)
true_images = torch.rand(32, 3, 299, 299)
art_images = torch.rand(32, 3, 299, 299)

inc_true = predictor(true_images).cpu().numpy()
inc_art = predictor(art_images).cpu().numpy()

inc_fid = frechet_distance(inc_true, inc_art)
```

If you are able to run this script with no errors, then your problem is probably related to the inputs you are feeding. What are yours `true_images` and `art_images`? How did you obtain those?

**Comment by Hossein-Askari** [comment]
> What this script does is it calculates the FID score for some random images:
> 
> ```python
> predictor = InceptionPredictor(output_dim=64)
> true_images = torch.rand(32, 3, 299, 299)
> art_images = torch.rand(32, 3, 299, 299)
> 
> inc_true = predictor(true_images).cpu().numpy()
> inc_art = predictor(art_images).cpu().numpy()
> 
> inc_fid = frechet_distance(inc_true, inc_art)
> ```
> 
> If you are able to run this script with no errors, then your problem is probably related to the inputs you are feeding. What are yours `true_images` and `art_images`? How did you obtain those?

**Comment by Hossein-Askari** [comment]
![111](https://user-images.githubusercontent.com/58578355/85452784-6201bb00-b5da-11ea-8f4a-f54a7500931e.png)

**Comment by Hossein-Askari** [comment]
> What this script does is it calculates the FID score for some random images:
> 
> ```python
> predictor = InceptionPredictor(output_dim=64)
> true_images = torch.rand(32, 3, 299, 299)
> art_images = torch.rand(32, 3, 299, 299)
> 
> inc_true = predictor(true_images).cpu().numpy()
> inc_art = predictor(art_images).cpu().numpy()
> 
> inc_fid = frechet_distance(inc_true, inc_art)
> ```
> 
> If you are able to run this script with no errors, then your problem is probably related to the inputs you are feeding. What are yours `true_images` and `art_images`? How did you obtain those?

I think the image uploaded above  clearly shows the error.
